language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

matrix:
    allow_failures:
        - php: 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - vendor/bin/phpcs --standard=PSR2 src
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

